spring.application.name=gestione_ordini_auth

#db
spring.datasource.url = ${MYSQL_URL_AUTH}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=${SERVLET_CONTEXT_PATH}
spring.jpa.open-in-view=false

#swagger
springdoc.api-docs.path=${API_DOCS_PATH}

#security
# Clé secrète JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}